# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Build Test

on: 
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set git identity
        run: |
          git fetch --all
          git config --global user.name 'christopher-roelofs'
          git config --global user.email 'christopher.roelofs@gmail.com'

      - name: Build web app
        run: |
          cd puck-ntag215-manager
          npm install --no-optional
          npm run build
